# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login(2).ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(400, 500)
        LoginDialog.setMinimumSize(QtCore.QSize(400, 500))
        LoginDialog.setMaximumSize(QtCore.QSize(400, 500))
        LoginDialog.setStyleSheet("QDialog {\n"
"    background-color: #f5f5f5;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(LoginDialog)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.logoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.logoLabel.setStyleSheet("QLabel {\n"
"    background-color: #4A7C9E;\n"
"    border-radius: 50px;\n"
"    padding: 20px;\n"
"}")
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap('./svg/logo.svg'))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.titleLabel = QtWidgets.QLabel(LoginDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: #888888;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.usernameInput = QtWidgets.QLineEdit(LoginDialog)
        self.usernameInput.setMinimumSize(QtCore.QSize(0, 45))
        self.usernameInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 4px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5DADE2;\n"
"}")
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout.addWidget(self.usernameInput)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.passwordInput = QtWidgets.QLineEdit(LoginDialog)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 45))
        self.passwordInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 4px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5DADE2;\n"
"}")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.loginButton = QtWidgets.QPushButton(LoginDialog)
        self.loginButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton {\n"
"    background-color: #5DADE2;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A9FD8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3A8FC8;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.forgotLabel = QtWidgets.QLabel(LoginDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.forgotLabel.setFont(font)
        self.forgotLabel.setStyleSheet("color: #5DADE2;")
        self.forgotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.forgotLabel.setObjectName("forgotLabel")
        self.verticalLayout.addWidget(self.forgotLabel)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.signupLabel = QtWidgets.QLabel(LoginDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.signupLabel.setFont(font)
        self.signupLabel.setStyleSheet("color: #888888;")
        self.signupLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.signupLabel.setOpenExternalLinks(False)
        self.signupLabel.setObjectName("signupLabel")
        self.verticalLayout.addWidget(self.signupLabel)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Login"))
        self.titleLabel.setText(_translate("LoginDialog", "Login"))
        self.usernameInput.setPlaceholderText(_translate("LoginDialog", "Username"))
        self.passwordInput.setPlaceholderText(_translate("LoginDialog", "Password"))
        self.loginButton.setText(_translate("LoginDialog", "LOG IN"))
        self.forgotLabel.setText(_translate("LoginDialog", "Forgot Login?"))
        self.signupLabel.setText(_translate("LoginDialog", "Don\'t have an account? <a href=\"#\" style=\"color: #5DADE2; text-decoration: none;\">Sign up</a>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec_())
