# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignupDialog(object):
    def setupUi(self, SignupDialog):
        SignupDialog.setObjectName("SignupDialog")
        SignupDialog.resize(400, 550)
        SignupDialog.setMinimumSize(QtCore.QSize(400, 550))
        SignupDialog.setMaximumSize(QtCore.QSize(400, 550))
        SignupDialog.setStyleSheet("QDialog {\n"
"    background-color: #f5f5f5;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(SignupDialog)
        self.verticalLayout.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logoLabel = QtWidgets.QLabel(SignupDialog)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.logoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.logoLabel.setStyleSheet("QLabel {\n"
"    background-color: #4A7C9E;\n"
"    border-radius: 50px;\n"
"    padding: 20px;\n"
"}")
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(".\\../../../../../../../../Downloads/logo.svg"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.titleLabel = QtWidgets.QLabel(SignupDialog)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: #888888;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.usernameInput = QtWidgets.QLineEdit(SignupDialog)
        self.usernameInput.setMinimumSize(QtCore.QSize(0, 45))
        self.usernameInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 4px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5DADE2;\n"
"}")
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout.addWidget(self.usernameInput)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.emailInput = QtWidgets.QLineEdit(SignupDialog)
        self.emailInput.setMinimumSize(QtCore.QSize(0, 45))
        self.emailInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 4px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5DADE2;\n"
"}")
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout.addWidget(self.emailInput)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.passwordInput = QtWidgets.QLineEdit(SignupDialog)
        self.passwordInput.setMinimumSize(QtCore.QSize(0, 45))
        self.passwordInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #d0d0d0;\n"
"    border-radius: 4px;\n"
"    padding: 8px 12px;\n"
"    background-color: white;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #5DADE2;\n"
"}")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.signupButton = QtWidgets.QPushButton(SignupDialog)
        self.signupButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.signupButton.setFont(font)
        self.signupButton.setStyleSheet("QPushButton {\n"
"    background-color: #5DADE2;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4A9FD8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3A8FC8;\n"
"}")
        self.signupButton.setObjectName("signupButton")
        self.verticalLayout.addWidget(self.signupButton)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.loginLabel = QtWidgets.QLabel(SignupDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: #888888;")
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setOpenExternalLinks(False)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout.addWidget(self.loginLabel)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(SignupDialog)
        QtCore.QMetaObject.connectSlotsByName(SignupDialog)

    def retranslateUi(self, SignupDialog):
        _translate = QtCore.QCoreApplication.translate
        SignupDialog.setWindowTitle(_translate("SignupDialog", "Sign Up"))
        self.titleLabel.setText(_translate("SignupDialog", "Sign Up"))
        self.usernameInput.setPlaceholderText(_translate("SignupDialog", "Username"))
        self.emailInput.setPlaceholderText(_translate("SignupDialog", "Email"))
        self.passwordInput.setPlaceholderText(_translate("SignupDialog", "Password"))
        self.signupButton.setText(_translate("SignupDialog", "SIGN UP"))
        self.loginLabel.setText(_translate("SignupDialog", "Already have an account? <a href=\"#\" style=\"color: #5DADE2; text-decoration: none;\">Log in</a>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignupDialog = QtWidgets.QDialog()
    ui = Ui_SignupDialog()
    ui.setupUi(SignupDialog)
    SignupDialog.show()
    sys.exit(app.exec_())
